# About this Continuous Assessment

|                 |                                                  |
|-----------------|--------------------------------------------------|
| Delivery method | Canvas submission of this file after completion. |
| Deadline        | As specified on Canvas.                          |
| ILOs            | Forward kinematics using  `numpy`.               |

#### Macros (do not touch these)
$\providecommand{\myvec}[1]{{\mathbf{\boldsymbol{{#1}}}}}$
$\providecommand{\mymatrix}[1]{{\mathbf{\boldsymbol{{#1}}}}}$

# Allowed packages
Do not modify these. Do not add or remove packages.

In [2]:
%pip install numpy
%pip install numpy --break-system-packages

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


# Allowed imports

Do not modify, add, or remove imports. Do not add imports anywhere else in this notebook.

In [3]:
import numpy as np
from math import pi, sin, cos

# Assigment description

Each cell is tagged for the assessment, so do not delete or otherwise tamper with the cells. The assigment is to add content to each of the Python cells as requested.

## Verify the spreadsheet

Your student ID will be used to assign you parameters. For each task, look into your row to see what you must implement.

## Converting a value from degrees to radians

Suppose that the `phi_deg` below is an angle in degrees. Its value in radians, `phi_rad`, should be calculated as follows.

**Do not** use lower precision approximations of $\pi$.

In [4]:
phi_deg = 45 # Value in degrees
phi_rad = phi_deg * pi / 180.0 # Value in radians
# Print is just to illustrate, it is not needed in answers.
print(f"The value {phi_deg} in degrees is {phi_rad} in radians.")

The value 45 in degrees is 0.7853981633974483 in radians.


## Task A

| Joint | $\theta$                | $d$      | $a$      | $\alpha$    |
|-------|-------------------------|----------|----------|-------------|
| 1     | $q_{A0}(t) + \phi_{A0}$ | $l_{A0}$ | 0        | 0           |
| 2     | $q_{A1}(t)$             | 0        | $l_{A1}$ | $\phi_{A1}$ |

For the DH-parameter table above, consider the following values obtained from your row in the spreadsheet.
- $\phi_{A0}$ and $\phi_{A1}$ are given in degrees by `ϕ_A0` and `ϕ_A1` respectively. **Convert them to radians before using them in your answer**.
- $l_{A0}$ and $l_{A1}$ are given in metres by `l_A0` and `l_A1` respectively. Use them as-is.

Calculate the forward kinematics of this manipulator, given by
$$\mymatrix{H}^{A0}_{A2} \in SE(3),$$
using the DH parameter table above.

Compute the FKM at $q_{A0} = \frac{\pi}{4}$ and $q_{A1} = -\frac{\pi}{2}$ and store it in `H_A0_A2` of the cell below. The answer must be of type `np.array`.


In [5]:
# Do not modify this(these) value(s). The original value(s) will be used for marking.
q_A0 = pi/4 # Do not convert this value
q_A1 = -pi/2 # Do not convert this value
# Solve the task here.



phi_A0_deg = -50
phi_A1_deg = 30
l_A0 = 0.8
l_A1 = 0.3

# Given joint values
q_A0 = pi/4
q_A1 = -pi/2

# Convert degrees to radians
phi_A0 = phi_A0_deg * pi / 180
phi_A1 = phi_A1_deg * pi / 180

# DH parameters
theta1 = q_A0 + phi_A0
d1 = l_A0
a1 = 0
alpha1 = 0

theta2 = q_A1
d2 = 0
a2 = l_A1
alpha2 = phi_A1

def DH(theta, d, a, alpha):
    return np.array([
        [cos(theta), -sin(theta)*cos(alpha),  sin(theta)*sin(alpha), a*cos(theta)],
        [sin(theta),  cos(theta)*cos(alpha), -cos(theta)*sin(alpha), a*sin(theta)],
        [0,           sin(alpha),             cos(alpha),            d],
        [0,           0,                      0,                     1]
    ])


# Add your final answer below. Replace the `None`.
H_A0_A2 = DH(theta1,d1,a1, alpha1) @ DH(theta2, d2, a2, alpha2)

print(H_A0_A2)

[[-0.08715574  0.86272992 -0.49809735 -0.02614672]
 [-0.9961947  -0.07547909  0.04357787 -0.29885841]
 [ 0.          0.5         0.8660254   0.8       ]
 [ 0.          0.          0.          1.        ]]


## Task B

Consider a `ROBOT_CLASSIFICATION_B` robot as specified in your spreadsheet.
- `PP` means joints 1 and 2 are prismatic.
- `PR` means that joint 1 is prismatic and joint 2 is revolute.

Consider the configuration space to be given by $q_{B0}(t)$ and $q_{B1}(t)$, for joints 1 and 2 respectively.

Adjust the DH-parameter table below to include the actuation of each axis by adding the corresponding configuration space value to the proper column with matching numerical index.

| Joint | $\theta$ | $d$ | $a$ | $\alpha$        |
|-------|----------|-----|-----|-----------------|
| 1     | $\pi$    | 0.3 | 0   | 0               |
| 2     | 0        | 0   | 0.5 | $\frac{\pi}{2}$ |

Compute the FKM (which outputs an element of SE(3)) at $q_{B0}(t) = 0.1$ and $q_{B1}(t) = 0.3$ and store it in `H_B0_B2` of the cell below. The answer must be of type `np.array`.




In [6]:
# Do not modify this(these) value(s). The original value(s) will be used for marking.
q_B0 = 0.1 # Do not convert this value
q_B1 = 0.3 # Do not convert this value
# Solve the task here.

# Given joint values
q_B0 = 0.1
q_B1 = 0.3

# PR robot:
# Joint 1 → Prismatic → add q_B0 to d
# Joint 2 → Revolute  → add q_B1 to theta

# DH parameters after actuation
theta1 = pi
d1 = 0.3 + q_B0
a1 = 0
alpha1 = 0

theta2 = q_B1
d2 = 0
a2 = 0.5
alpha2 = pi/2

def DH(theta, d, a, alpha):
    return np.array([
        [cos(theta), -sin(theta)*cos(alpha),  sin(theta)*sin(alpha), a*cos(theta)],
        [sin(theta),  cos(theta)*cos(alpha), -cos(theta)*sin(alpha), a*sin(theta)],
        [0,           sin(alpha),             cos(alpha),            d],
        [0,           0,                      0,                     1]
    ])



# Add your final answer below. Replace the `None`.
H_B0_B2 = DH(theta1, d1, a1, alpha1) @ DH(theta2, d2, a2, alpha2)

print(H_B0_B2)

[[-9.55336489e-01  1.80953938e-17 -2.95520207e-01 -4.77668245e-01]
 [-2.95520207e-01 -5.84974887e-17  9.55336489e-01 -1.47760103e-01]
 [ 0.00000000e+00  1.00000000e+00  6.12323400e-17  4.00000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
